import csv
import json
import requests
from datetime import datetime
import os

# --- 1. CONFIGURATION ---
# IMPORTANT: Replace this with the URL generated by your n8n Webhook node (Step 3)!
N8N_WEBHOOK_URL = "https://bsadeghi67.app.n8n.cloud/webhook-test/daily_test" 

# Define all three test configurations in a single array
TEST_CONFIGS = [
    {
        "Line_ID": "Line_B",
        "RAW_CSV_FILE": "instrument_output_line_B.csv",
        "Test_Code": "V_CORE_STABILITY",
        "Unit": "V",
        "CSV_Column_Header": "Measured_Value" # Column used for calculation
    } ]
   


# --- 2. CORE PROCESSING FUNCTION ---
def process_single_test(config):
    """
    Reads CSV, extracts value, builds JSON, and sends payload for a single test.
    """
    
    measured_values = [] 
    csv_file = config["RAW_CSV_FILE"]
    column_header = config["CSV_Column_Header"]

    print(f"\n--- Processing Test: {config['Test_Code']} on {config['Line_ID']} ---")

    try:
        with open(csv_file, mode='r', encoding='utf-8') as file:
            csv_reader = csv.reader(file)
            header = next(csv_reader) # Read header row
            
            try:
                value_column_index = header.index(column_header)
            except ValueError:
                print(f"Error: Required column ('{column_header}') not found in {csv_file}. Skipping.")
                return

            for row in csv_reader:
                try:
                    measured_values.append(float(row[value_column_index]))
                except (ValueError, IndexError):
                    continue

    except FileNotFoundError:
        print(f"Error: Raw CSV file {csv_file} not found. Ensure all three files are present. Skipping.")
        return
    
    if not measured_values:
        print("Error: No valid numeric data found for processing. Skipping.")
        return

    # FINAL VALUE EXTRACTION LOGIC (Using Average for simplicity in this general script)
    # *Note: For V_RIPPLE_MAX, using MAX or the last reading might be more appropriate,
    # but we use average here to keep the code unified.*
    final_measured_value = sum(measured_values) / len(measured_values)
    
    # --- 3. CONSTRUCT AND SEND JSON PAYLOAD ---
    payload = {
        "Line_ID": config["Line_ID"],
        "DUT_SN": f"AUTO-{config['Line_ID']}-TEST-{int(datetime.now().timestamp())}", # Auto-generate SN for testing
        "Test_Code": config["Test_Code"],
        "Measured_Value": round(final_measured_value, 4), 
        "Unit": config["Unit"],
        "Test_Time": datetime.now().isoformat()
    }
    
    print(f"Payload built: {payload['DUT_SN']} -> {payload['Measured_Value']} {payload['Unit']}")

    try:
        response = requests.post(N8N_WEBHOOK_URL, json=payload)
        
        if response.status_code == 200:
            print(f"✅ Success: Data sent to n8n.")
        else:
            print(f"❌ Failed: Status Code {response.status_code}. Response: {response.text}")

    except requests.exceptions.RequestException as e:
        print(f"❌ Failed to connect to n8n Webhook: {e}")


def main():
    """Main function to iterate through all configurations."""
    if N8N_WEBHOOK_URL == "YOUR_N8N_WEBHOOK_URL_HERE":
        print("CRITICAL ERROR: Please replace 'YOUR_N8N_WEBHOOK_URL_HERE' with your actual n8n Webhook URL before running.")
        return

    for config in TEST_CONFIGS:
        process_single_test(config)

if __name__ == "__main__":
    main()